// index.js
import './plugins/admin.js'
import './plugins/ai.js'
import './plugins/antlink.js'
import './plugins/audio2ptt.js'
import './plugins/date.js'
import './plugins/facebook.js'
import './plugins/fun.js'
import './plugins/hello.js'
import './plugins/hidetag.js'
import './plugins/insta.js'
import './plugins/media-downloader.js'
import './plugins/media.js'
import './plugins/menu.js'
import './plugins/music.js'
import './plugins/online.js'
import './plugins/pdfdownload.js'
import './plugins/ping.js'
import './plugins/qrgen.js'
import './plugins/searchmusic.js'
import './plugins/security.js'
import './plugins/shorturl.js'
import './plugins/time.js'
import './plugins/tiktok.js'
import './plugins/tool.js'
import './plugins/translate.js'
import './plugins/ttsaudio.js'
import './plugins/video.js'

// Start your bot logic here...
console.log("Fatuma Bot is ready with all plugins loaded!")
