export default  async (sock, msg, body, from, prefix) => {
  const commands = {
    [`${prefix}joke`]: "Why don’t scientists trust atoms? Because they make up everything!",
    [`${prefix}darkjoke`]: "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    [`${prefix}quote`]: "“The best way to get started is to quit talking and begin doing.” – Walt Disney",
    [`${prefix}roast`]: "You have something on your chin… no, the third one down.",
    [`${prefix}pickup`]: "Are you a magician? Because whenever I look at you, everyone else disappears!",
    [`${prefix}flirt`]: "If you were a vegetable, you’d be a cute-cumber!",
    [`${prefix}troll`]: "You're as useless as the 'ueue' in 'queue'.",
    [`${prefix}brain`]: "Did you know? Your brain uses 20% of your body’s energy but makes up only 2% of your body weight.",
    [`${prefix}simpgirl`]: "You're the reason I check my phone every five seconds.",
    [`${prefix}compliment`]: "You're like sunshine on a rainy day.",
    [`${prefix}genius`]: "The difference between stupidity and genius is that genius has its limits. - Einstein",
    [`${prefix}riddle`]: "I speak without a mouth and hear without ears. I have nobody, but I come alive with the wind. What am I?",
    [`${prefix}fact`]: "Octopuses have three hearts and blue blood.",
    [`${prefix}insult`]: "You're the reason shampoo has instructions.",
    [`${prefix}truth`]: "Have you ever lied to someone you love?",
    [`${prefix}dare`]: "Send a voice note saying 'I'm Batman' in your deepest voice.",
    [`${prefix}proverb`]: "A journey of a thousand miles begins with a single step.",
    [`${prefix}status`]: "Feeling happy and blessed!",
    [`${prefix}random`]: "Sometimes we just need a random moment to smile.",
    [`${prefix}vibe`]: "Your vibe attracts your tribe.",
    [`${prefix}energy`]: "Radiate positive energy today!",
    [`${prefix}laugh`]: "Why did the chicken join a band? Because it had the drumsticks!",
    [`${prefix}cry`]: "Even the strongest cry. It's okay not to be okay.",
    [`${prefix}motivate`]: "Push yourself, because no one else is going to do it for you.",
    [`${prefix}flirtboy`]: "You're hotter than the bottom of my laptop.",
    [`${prefix}simpboy`]: "I’d cross oceans for you, and maybe even seas of lava.",
    [`${prefix}breakup`]: "If you love something, let it go. If it comes back, it's yours. If not, it was never meant to be.",
    [`${prefix}relationship`]: "Healthy relationships start with healthy boundaries.",
    [`${prefix}truth2`]: "The hardest truth is sometimes better than the sweetest lie.",
    [`${prefix}dare2`]: "Send the 3rd emoji in your recent list to your crush.",
    [`${prefix}cringe`]: "Did it hurt when you fell… from the cringe department?",
    [`${prefix}reply`]: "Nice try! But I’m not falling for that one.",
    [`${prefix}emotional`]: "Sometimes emotions speak louder than words.",
    [`${prefix}cute`]: "You're cuter than a basket of puppies!",
    [`${prefix}crazy`]: "You're as crazy as a fox on Red Bull!",
    [`${prefix}savage`]: "I’d agree with you, but then we’d both be wrong.",
    [`${prefix}funny`]: "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    [`${prefix}dumb`]: "You bring everyone so much joy… when you leave the room.",
    [`${prefix}smile`]: "Smile! It increases your face value.",
    [`${prefix}hot`]: "Warning: Too hot to handle!",
    [`${prefix}cold`]: "Colder than my ex’s heart!",
    [`${prefix}emoji`]: "Here’s a random emoji combo: ️‍🔥 + + = mood",
    [`${prefix}respect`]: "Respect is earned, not given.",
    [`${prefix}truth3`]: "What’s one thing you’ve never told anyone?",
    [`${prefix}dare3`]: "Text someone randomly and say 'I love pineapples.'",
    [`${prefix}silly`]: "Silly is my middle name!",
    [`${prefix}trap`]: "You've activated my trap card!",
    [`${prefix}badass`]: "Walk in like you own the place.",
    [`${prefix}goodmorning`]: "Rise and shine! Today is a new beginning.",
    [`${prefix}goodnight`]: "Sweet dreams and sleep tight!",
    [`${prefix}wisdom`]: "Knowledge is knowing a tomato is a fruit. Wisdom is not putting it in a fruit salad.",
    [`${prefix}deep`]: "Sometimes the deepest pain hides behind the brightest smile.",
    [`${prefix}blessed`]: "Feeling blessed beyond measure.",
    [`${prefix}mad`]: "I’m not mad, just differently sane.",
    [`${prefix}sad`]: "It’s okay to feel sad sometimes. Embrace it.",
    [`${prefix}inspire`]: "Your potential is endless.",
    [`${prefix}fire`]: "You're on fire today — metaphorically!",
    [`${prefix}ice`]: "Stay cool, ice queen/king.",
    [`${prefix}angel`]: "Did it hurt when you fell from heaven?",
    [`${prefix}devil`]: "Too hot for heaven, too cool for hell.",
  };

  if (commands[body]) {
    await sock.sendMessage(from, { text: commands[body] }, { quoted: msg });
  }
};
